### ISSUE TITLE
Add MET Survey banner in EPIC

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/eagle-public#593]
**Overview**
Integrate the survey banner in the landing page of EPIC public portal. The design can be found in the below URL
[https://xd.adobe.com/view/e2831462-9efd-4312-9879-bb765be852bd-b7d0/specs/](url)

The survey URL should be able to be integrated from externally, like using an environment variable. 
We can add ENV variables in the deployment config and add the line code in the below mentioned file.

[https://github.com/bcgov/eagle-public/blob/develop/openshift/templates/nginx-runtime/s2i/bin/run](url)

Plus, we need to add this in the template file for future deployments.
[https://github.com/bcgov/eagle-public/blob/develop/openshift/templates/angular-on-nginx/angular-on-nginx-deploy.json](url)

This file will get executed and generate a js file, which will get bundled during the build process and cause the corresponding local storage item to be created in the browser. You can see, they have injected the backend api URL in the same way.

**Comment by carlygreenehill** [comment]
Code is done > it just hasn't been pushed yet > waiting on the SURVEY URL from team MET
