### ISSUE TITLE
The Resource Forecast should not show the current month in the Q1 Columns

### ISSUE THREAD

**Issue by Connor1892** [bcgov/eagle-public#634]
The Q1 section of the Resource Forecast should show X+1, X+2, X+3 where X is the current month.

If I'm looking at the forecast on July 1st, I should see Aug, Sept, Oct in Q1 and Nov/Dec/Jan in Q2.

**Comment by dinesh-aot** [comment]
@Connor1892 Could you please verify it with the given report 
https://bcgov-my.sharepoint.com/:b:/g/personal/geoff_l_mcdonald_gov_bc_ca/Ec-4dSnhY95FqEjMgu1tXlsBCt3ITMaqBDnwY8qYLWJpLw

This is the sample shared by Geoff before. This is a report taken in the month of January.

**Comment by Connor1892** [comment]
![EPIC-FLOW#634](https://user-images.githubusercontent.com/126211473/228305852-da9a9da6-6d65-4578-8e37-98abe4937642.PNG)

**Comment by Connor1892** [comment]
this is back to showing the current month in the Q1 columns
