### ISSUE TITLE
Change EPIC.public Contact Page

### ISSUE THREAD

**Issue by Connor1892** [bcgov/eagle-public#640]
**As a** member of the public

**I want** the correct email on the contact page

**so that** I can get in touch with the EAO about my concerns

### Scenario 1: 

GIVEN I want to contact the EAO about EPIC.public
WHEN I go to https://www.projects.eao.gov.bc.ca/contact
THEN I see EAO.EPICsystem@gov.bc.ca

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by EAO-App-Admin** [comment]
Tested, working as intended
